//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonosDeRemision
    {
        public int idAbonoDeRemision { get; set; }
        public string folio { get; set; }
        public int idRemision { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal monto { get; set; }
        public int idMoneda { get; set; }
        public int idFormaPago { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idEstatusDeAbono { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EstatusDeAbono EstatusDeAbono { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Remisione Remisione { get; set; }
    }
}
