//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddendaDeCliente
    {
        public int idCliente { get; set; }
        public int idAddenda { get; set; }
        public string xslt { get; set; }
    
        public virtual Addenda Addenda { get; set; }
        public virtual Cliente Cliente { get; set; }
    }
}
