//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ajuste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ajuste()
        {
            this.DetallesDeAjustes = new HashSet<DetallesDeAjuste>();
            this.Pedimentos = new HashSet<Pedimento>();
        }
    
        public int idAjuste { get; set; }
        public string folio { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idTipoDeAjuste { get; set; }
        public int idEstatusDeAjuste { get; set; }
    
        public virtual EstatusDeAjuste EstatusDeAjuste { get; set; }
        public virtual TiposDeAjuste TiposDeAjuste { get; set; }
        public virtual CancelacionesDeAjuste CancelacionesDeAjuste { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeAjuste> DetallesDeAjustes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedimento> Pedimentos { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
