//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cliente()
        {
            this.AddendaDeClientes = new HashSet<AddendaDeCliente>();
            this.Cotizaciones = new HashSet<Cotizacione>();
            this.CuentasDeCorreos = new HashSet<CuentasDeCorreo>();
            this.Facturas = new HashSet<Factura>();
            this.NotasDeCreditoes = new HashSet<NotasDeCredito>();
            this.Pagos = new HashSet<Pago>();
            this.NotasDeDescuentoes = new HashSet<NotasDeDescuento>();
            this.CodigosDeArticuloPorClientes = new HashSet<CodigosDeArticuloPorCliente>();
            this.Remisiones = new HashSet<Remisione>();
            this.Pedidos = new HashSet<Pedido>();
        }
    
        public int idCliente { get; set; }
        public string codigo { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public string telefono { get; set; }
        public string correoElectronico { get; set; }
        public string contacto { get; set; }
        public string condicionDePago { get; set; }
        public int idDomicilio { get; set; }
        public int idListaDePrecio { get; set; }
        public bool activo { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public Nullable<decimal> limiteCredito { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public Nullable<int> idUsoCFDI { get; set; }
        public Nullable<int> idRegimen { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AddendaDeCliente> AddendaDeClientes { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        public virtual ListasDePrecio ListasDePrecio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacione> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasDeCorreo> CuentasDeCorreos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas { get; set; }
        public virtual UsosCFDI UsosCFDI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasDeCredito> NotasDeCreditoes { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pago> Pagos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasDeDescuento> NotasDeDescuentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodigosDeArticuloPorCliente> CodigosDeArticuloPorClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remisione> Remisiones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedidos { get; set; }
        public virtual Regimene Regimene { get; set; }
    }
}
