//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Compra()
        {
            this.AbonosDeCompras = new HashSet<AbonosDeCompra>();
            this.DetallesDeCompras = new HashSet<DetallesDeCompra>();
            this.Pedimentos = new HashSet<Pedimento>();
        }
    
        public int idCompra { get; set; }
        public string folio { get; set; }
        public int idProveedor { get; set; }
        public int idMoneda { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idEstatusDeCompra { get; set; }
        public int idUsuarioRegistro { get; set; }
        public Nullable<int> idOrdenDeCompra { get; set; }
        public decimal cargos { get; set; }
        public decimal descuentos { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonosDeCompra> AbonosDeCompras { get; set; }
        public virtual CancelacionesDeCompra CancelacionesDeCompra { get; set; }
        public virtual EstatusDeCompra EstatusDeCompra { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeCompra> DetallesDeCompras { get; set; }
        public virtual OrdenesDeCompra OrdenesDeCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedimento> Pedimentos { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
