//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Configuracione()
        {
            this.Certificados = new HashSet<Certificado>();
            this.CuentasGuardians = new HashSet<CuentasGuardian>();
            this.Regimenes = new HashSet<Regimene>();
            this.Series = new HashSet<Series>();
            this.FormatosPorConfiguracions = new HashSet<FormatosPorConfiguracion>();
        }
    
        public int idConfiguracion { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public decimal tipoDeCambio { get; set; }
        public string usuarioPAC { get; set; }
        public string contraseñaPAC { get; set; }
        public int idDomicilio { get; set; }
        public string telefono { get; set; }
        public int idOpcionCostoAumenta { get; set; }
        public int idOpcionCostoDisminuye { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Certificado> Certificados { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CuentasGuardian> CuentasGuardians { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Regimene> Regimenes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Series> Series { get; set; }
        public virtual OpcionesCosto OpcionesCosto { get; set; }
        public virtual OpcionesCosto OpcionesCosto1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatosPorConfiguracion> FormatosPorConfiguracions { get; set; }
    }
}
