//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesDeFactura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallesDeFactura()
        {
            this.PedimentoPorDetalleDeFacturas = new HashSet<PedimentoPorDetalleDeFactura>();
            this.Impuestos = new HashSet<Impuesto>();
        }
    
        public int idDetalleDeFactura { get; set; }
        public int idArticulo { get; set; }
        public decimal cantidad { get; set; }
        public decimal precioUnitario { get; set; }
        public decimal descuento { get; set; }
        public int idFactura { get; set; }
    
        public virtual CuentaPredialPorDetalle CuentaPredialPorDetalle { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedimentoPorDetalleDeFactura> PedimentoPorDetalleDeFacturas { get; set; }
        public virtual ComentariosPorDetalleDeFactura ComentariosPorDetalleDeFactura { get; set; }
        public virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impuesto> Impuestos { get; set; }
        public virtual Factura Factura { get; set; }
    }
}
