//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresasAsociada
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmpresasAsociada()
        {
            this.Traspasos = new HashSet<Traspaso>();
            this.Traspasos1 = new HashSet<Traspaso>();
            this.SolicitudesDeTraspasoes = new HashSet<SolicitudesDeTraspaso>();
        }
    
        public int idEmpresaAsociada { get; set; }
        public string nombre { get; set; }
        public string servidor { get; set; }
        public string baseDeDatos { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public bool activa { get; set; }
        public Nullable<int> idEmpresaLocal { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traspaso> Traspasos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traspaso> Traspasos1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SolicitudesDeTraspaso> SolicitudesDeTraspasoes { get; set; }
    }
}
