//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatosPorConfiguracion
    {
        public int idConfiguracion { get; set; }
        public int idReporte { get; set; }
        public int idFormato { get; set; }
    
        public virtual Configuracione Configuracione { get; set; }
        public virtual Formato Formato { get; set; }
        public virtual Reporte Reporte { get; set; }
    }
}
