//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Formato()
        {
            this.FormatosPorConfiguracions = new HashSet<FormatosPorConfiguracion>();
        }
    
        public int idFormato { get; set; }
        public int idReporte { get; set; }
        public string archivo { get; set; }
        public string descripcion { get; set; }
    
        public virtual Reporte Reporte { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormatosPorConfiguracion> FormatosPorConfiguracions { get; set; }
    }
}
