//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Impuesto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Impuesto()
        {
            this.Articulos = new HashSet<Articulo>();
            this.DetallesDeCompras = new HashSet<DetallesDeCompra>();
            this.DetallesDeCotizacions = new HashSet<DetallesDeCotizacion>();
            this.DetallesDeFacturas = new HashSet<DetallesDeFactura>();
            this.DetallesDeOrdenDeCompras = new HashSet<DetallesDeOrdenDeCompra>();
            this.DetallesDePedidoes = new HashSet<DetallesDePedido>();
            this.DetallesDeRemisions = new HashSet<DetallesDeRemision>();
            this.DetallesDeNotaDeCreditoes = new HashSet<DetallesDeNotaDeCredito>();
        }
    
        public int idImpuesto { get; set; }
        public string codigo { get; set; }
        public string nombre { get; set; }
        public decimal valor { get; set; }
        public bool activo { get; set; }
        public int idTipoDeImpuesto { get; set; }
        public int idTipoFactor { get; set; }
    
        public virtual TiposDeImpuesto TiposDeImpuesto { get; set; }
        public virtual TiposFactor TiposFactor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Articulo> Articulos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeCompra> DetallesDeCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeCotizacion> DetallesDeCotizacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeFactura> DetallesDeFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeOrdenDeCompra> DetallesDeOrdenDeCompras { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDePedido> DetallesDePedidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeRemision> DetallesDeRemisions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeNotaDeCredito> DetallesDeNotaDeCreditoes { get; set; }
    }
}
