//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDeCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NotasDeCredito()
        {
            this.DatosExtraPorNotaDeCreditoes = new HashSet<DatosExtraPorNotaDeCredito>();
            this.DetallesDeNotaDeCreditoes = new HashSet<DetallesDeNotaDeCredito>();
            this.NotasDeDescuentoes = new HashSet<NotasDeDescuento>();
        }
    
        public int idNotaDeCredito { get; set; }
        public string serie { get; set; }
        public int folio { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string cadenaOriginal { get; set; }
        public int idFormaDePago { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idEmpresa { get; set; }
        public int idCliente { get; set; }
        public int idMoneda { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idRegimen { get; set; }
        public Nullable<int> idFactura { get; set; }
        public decimal importe { get; set; }
        public string descripcion { get; set; }
        public int idEstatusDeNotaDeCredito { get; set; }
        public Nullable<int> idCuentaBancaria { get; set; }
    
        public virtual CancelacionesDeNotaDeCredito CancelacionesDeNotaDeCredito { get; set; }
        public virtual CuentasBancaria CuentasBancaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosExtraPorNotaDeCredito> DatosExtraPorNotaDeCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeNotaDeCredito> DetallesDeNotaDeCreditoes { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstatusDeNotaDeCredito EstatusDeNotaDeCredito { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual FormasPago FormasPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Regimene Regimene { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TimbresDeNotasDeCredito TimbresDeNotasDeCredito { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasDeDescuento> NotasDeDescuentoes { get; set; }
    }
}
