//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedimentoPorDetalleDeAjuste
    {
        public int idPedimento { get; set; }
        public int idDetalleDeAjuste { get; set; }
        public decimal cantidad { get; set; }
    
        public virtual DetallesDeAjuste DetallesDeAjuste { get; set; }
        public virtual Pedimento Pedimento { get; set; }
    }
}
