//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Privilegio
    {
        public int idUsuario { get; set; }
        public int idPantalla { get; set; }
        public int idPermiso { get; set; }
    
        public virtual Pantalla Pantalla { get; set; }
        public virtual Permiso Permiso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
