//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proveedore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Proveedore()
        {
            this.CodigosDeArticuloPorProveedors = new HashSet<CodigosDeArticuloPorProveedor>();
            this.Compras = new HashSet<Compra>();
            this.OrdenesDeCompras = new HashSet<OrdenesDeCompra>();
        }
    
        public int idProveedor { get; set; }
        public string codigo { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public int idDomicilio { get; set; }
        public bool activo { get; set; }
        public string telefono { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CodigosDeArticuloPorProveedor> CodigosDeArticuloPorProveedors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual Domicilio Domicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdenesDeCompra> OrdenesDeCompras { get; set; }
    }
}
