//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimbresDeAbonosDeFactura
    {
        public int idTimbreDeAbonoDeFactura { get; set; }
        public string serie { get; set; }
        public int folio { get; set; }
        public string noCertificado { get; set; }
        public string sello { get; set; }
        public string cadenaOriginalAbono { get; set; }
        public string version { get; set; }
        public string selloSAT { get; set; }
        public string selloCFD { get; set; }
        public string noCertificadoSAT { get; set; }
        public string UUID { get; set; }
        public System.DateTime fechaTimbrado { get; set; }
        public string cadenaOriginal { get; set; }
        public string RfcProvCertif { get; set; }
        public string Leyenda { get; set; }
    
        public virtual AbonosDeFactura AbonosDeFactura { get; set; }
        public virtual CancelacionesDeTimbreDeAbonosDeFactura CancelacionesDeTimbreDeAbonosDeFactura { get; set; }
    }
}
