//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Traspaso
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Traspaso()
        {
            this.DatosExtraPorTraspasoes = new HashSet<DatosExtraPorTraspaso>();
            this.DetallesDeTraspasoes = new HashSet<DetallesDeTraspaso>();
        }
    
        public int idTraspaso { get; set; }
        public int folio { get; set; }
        public string descripcion { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idEstatusDeTraspaso { get; set; }
        public int idEmpresaAsociadaOrigen { get; set; }
        public int idEmpresaAsociadaDestino { get; set; }
        public Nullable<int> folioRemoto { get; set; }
        public Nullable<System.DateTime> fechaHoraRemoto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosExtraPorTraspaso> DatosExtraPorTraspasoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeTraspaso> DetallesDeTraspasoes { get; set; }
        public virtual EmpresasAsociada EmpresasAsociada { get; set; }
        public virtual EmpresasAsociada EmpresasAsociada1 { get; set; }
        public virtual EstatusDeTraspaso EstatusDeTraspaso { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
