//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwArticulosOrdenado
    {
        public int idArticulo { get; set; }
        public Nullable<decimal> ordenados { get; set; }
        public Nullable<decimal> comprados { get; set; }
    }
}
