//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwComprasPorArticulo
    {
        public int idArticulo { get; set; }
        public string razonSocial { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal cantidad { get; set; }
        public string unidad { get; set; }
        public decimal costoUnitario { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string moneda { get; set; }
        public string folio { get; set; }
        public decimal tipoDeCambio { get; set; }
        public string nombreDeUsuario { get; set; }
    }
}
