//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwCotizacionesPorPeriodo
    {
        public int Folio { get; set; }
        public string Cliente { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Moneda { get; set; }
        public string Usuario { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idMoneda { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idRemision { get; set; }
    }
}
