//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwComprobantesCancelado
    {
        public System.DateTime cancelacion { get; set; }
        public System.DateTime emision { get; set; }
        public string tipo { get; set; }
        public string folio { get; set; }
        public string codigo { get; set; }
        public string razonSocial { get; set; }
        public Nullable<decimal> total { get; set; }
        public string moneda { get; set; }
    }
}
