//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwDetallesDePedidosPorSurtir
    {
        public int idPedido { get; set; }
        public int idArticulo { get; set; }
        public int idDetalleDePedido { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> cantidadSurtida { get; set; }
        public Nullable<decimal> cantidadPorSurtir { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public int idMoneda { get; set; }
    }
}
