//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwInventario
    {
        public int idArticulo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public bool importado { get; set; }
        public int idMoneda { get; set; }
        public string moneda { get; set; }
        public string unidad { get; set; }
        public decimal costoUnitario { get; set; }
        public Nullable<System.DateTime> ultimaCompra { get; set; }
        public Nullable<decimal> pendientes { get; set; }
        public decimal minimo { get; set; }
        public decimal maximo { get; set; }
        public decimal puntoDeReorden { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public int requiereOrden { get; set; }
    }
}
