//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwListaParcialidade
    {
        public string SerieFactura { get; set; }
        public int FolioFactura { get; set; }
        public int idFactura { get; set; }
        public string FolioFacturaTexto { get; set; }
        public decimal Total { get; set; }
        public int idMoneda { get; set; }
        public string Moneda { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string Fecha { get; set; }
        public string Cliente { get; set; }
        public string CodigoCliente { get; set; }
        public int idCliente { get; set; }
        public int FolioAbono { get; set; }
        public string SerieAbono { get; set; }
        public string FolioAbonoTexto { get; set; }
        public int idAbonoDeFactura { get; set; }
        public int TipoDeAbono { get; set; }
    }
}
