//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwListasDePrecioPorArticuloConExistencia
    {
        public int idArticulo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public Nullable<decimal> PrecioA { get; set; }
        public Nullable<decimal> PrecioB { get; set; }
        public Nullable<decimal> PrecioC { get; set; }
        public Nullable<decimal> PrecioD { get; set; }
        public int idMoneda { get; set; }
        public bool inventariado { get; set; }
        public Nullable<decimal> existencia { get; set; }
    }
}
