//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwListaArticulo
    {
        public int idArticulo { get; set; }
        public string Codigo { get; set; }
        public string Descripcion { get; set; }
        public string UnidadDeMedida { get; set; }
        public Nullable<decimal> PrecioUnitario { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Existencia { get; set; }
        public bool Activo { get; set; }
    }
}
