//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteEstatusDeLaEmpresaPedido
    {
        public Nullable<decimal> importe { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idMoneda { get; set; }
        public int idPedido { get; set; }
        public Nullable<decimal> impuestosTrasladados { get; set; }
        public Nullable<decimal> impuestosRetenidos { get; set; }
    }
}
