//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteAvaluo
    {
        public int idArticulo { get; set; }
        public string descripcionArticulo { get; set; }
        public string codigoArticulo { get; set; }
        public bool importado { get; set; }
        public int idMoneda { get; set; }
        public Nullable<decimal> precioUnitario { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public Nullable<decimal> entradas { get; set; }
        public Nullable<decimal> salidas { get; set; }
    }
}
