//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteListaDePrecio
    {
        public int idArticulo { get; set; }
        public string descripcionArticulo { get; set; }
        public string codigoArticulo { get; set; }
        public Nullable<decimal> precioUnitarioA { get; set; }
        public Nullable<decimal> precioUnitarioB { get; set; }
        public Nullable<decimal> precioUnitarioC { get; set; }
        public Nullable<decimal> precioUnitarioD { get; set; }
        public int idMoneda { get; set; }
        public bool inventariado { get; set; }
        public Nullable<decimal> existencia { get; set; }
    }
}
