//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteInventarioFisico
    {
        public int idArticulo { get; set; }
        public string codigo { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> existencia { get; set; }
        public string unidadMedida { get; set; }
        public Nullable<int> idClasificacion { get; set; }
        public bool inventariado { get; set; }
    }
}
