//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSaldosPorProveedorPorMoneda
    {
        public int idProveedor { get; set; }
        public string codigo { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public string rfc { get; set; }
        public int idDomicilio { get; set; }
        public bool activo { get; set; }
        public int idMoneda { get; set; }
        public string descripcion { get; set; }
        public Nullable<decimal> total { get; set; }
        public Nullable<decimal> abonado { get; set; }
        public Nullable<System.DateTime> mayorAntiguedad { get; set; }
        public Nullable<System.DateTime> menorAntiguedad { get; set; }
    }
}
