//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwVentasActivasPorCliente
    {
        public string TipoTransaccion { get; set; }
        public string Folio { get; set; }
        public string Fecha { get; set; }
        public System.DateTime FechaHora { get; set; }
        public int idCliente { get; set; }
        public Nullable<decimal> Total { get; set; }
        public Nullable<decimal> Abonado { get; set; }
        public Nullable<decimal> Saldo { get; set; }
        public int idMoneda { get; set; }
        public string Moneda { get; set; }
    }
}
