//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionesDeNotaDeDescuento
    {
        public int idNotaDeDescuento { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string motivo { get; set; }
    
        public virtual NotasDeDescuento NotasDeDescuento { get; set; }
    }
}
