//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesDeAjuste
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallesDeAjuste()
        {
            this.PedimentoPorDetalleDeAjustes = new HashSet<PedimentoPorDetalleDeAjuste>();
        }
    
        public int idDetalleDeAjuste { get; set; }
        public int idAjuste { get; set; }
        public int idArticulo { get; set; }
        public decimal cantidad { get; set; }
        public decimal costoUnitario { get; set; }
        public int idMoneda { get; set; }
    
        public virtual Ajuste Ajuste { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedimentoPorDetalleDeAjuste> PedimentoPorDetalleDeAjustes { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
