//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AbonosDeCompra
    {
        public int idAbonoDeCompra { get; set; }
        public string folio { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal monto { get; set; }
        public int idMoneda { get; set; }
        public decimal tipoDeCambio { get; set; }
        public string referencia { get; set; }
        public bool cancelado { get; set; }
        public int idCompra { get; set; }
        public int idFormaPago { get; set; }
        public int idUsuarioRegistro { get; set; }
    
        public virtual FormasPago FormasPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Compra Compra { get; set; }
    }
}
