//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentasGuardian
    {
        public int idCuentaGuardian { get; set; }
        public int idConfiguracion { get; set; }
        public string servidor { get; set; }
        public bool ssl { get; set; }
        public int puerto { get; set; }
        public string direccion { get; set; }
        public string contrasena { get; set; }
    
        public virtual Configuracione Configuracione { get; set; }
    }
}
