//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwEntradasPorArticulo
    {
        public int idArticulo { get; set; }
        public Nullable<decimal> entradasCompras { get; set; }
        public Nullable<decimal> salidasCompras { get; set; }
        public Nullable<decimal> totalCompras { get; set; }
        public Nullable<decimal> entradasAjustes { get; set; }
        public Nullable<decimal> salidasAjustes { get; set; }
        public Nullable<decimal> totalAjustes { get; set; }
        public Nullable<decimal> entradasTraspasos { get; set; }
        public Nullable<decimal> totalEntradas { get; set; }
        public Nullable<decimal> entradasNotasDeCredito { get; set; }
    }
}
