//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factura
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factura()
        {
            this.AbonosDeFacturas = new HashSet<AbonosDeFactura>();
            this.Cotizaciones = new HashSet<Cotizacione>();
            this.DatosExtraPorFacturas = new HashSet<DatosExtraPorFactura>();
            this.DetallesDeFacturas = new HashSet<DetallesDeFactura>();
            this.Facturas1 = new HashSet<Factura>();
            this.NotasDeCreditoes = new HashSet<NotasDeCredito>();
            this.NotasDeDescuentoes = new HashSet<NotasDeDescuento>();
            this.Remisiones = new HashSet<Remisione>();
        }
    
        public int idFactura { get; set; }
        public string serie { get; set; }
        public int folio { get; set; }
        public System.DateTime fechaHora { get; set; }
        public string noCertificado { get; set; }
        public string sello { get; set; }
        public string cadenaOriginal { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idMoneda { get; set; }
        public int idCliente { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idMetodoPago { get; set; }
        public int idEstatusDeFactura { get; set; }
        public int idEmpresa { get; set; }
        public int idUsoCFDI { get; set; }
        public int idRegimen { get; set; }
        public Nullable<int> idComprobanteOriginal { get; set; }
        public Nullable<int> idTipoRelacion { get; set; }
        public string ordenDeCompra { get; set; }
        public Nullable<int> idPedido { get; set; }
        public Nullable<int> idVendedor { get; set; }
        public int idEstatusCrediticio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AbonosDeFactura> AbonosDeFacturas { get; set; }
        public virtual CancelacionesDeFactura CancelacionesDeFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cotizacione> Cotizaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosExtraPorFactura> DatosExtraPorFacturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeFactura> DetallesDeFacturas { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstatusDeFactura EstatusDeFactura { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factura> Facturas1 { get; set; }
        public virtual Factura Factura1 { get; set; }
        public virtual MetodosPago MetodosPago { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual Regimene Regimene { get; set; }
        public virtual TiposRelacion TiposRelacion { get; set; }
        public virtual UsosCFDI UsosCFDI { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual TimbresDeFactura TimbresDeFactura { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasDeCredito> NotasDeCreditoes { get; set; }
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotasDeDescuento> NotasDeDescuentoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Remisione> Remisiones { get; set; }
        public virtual Pedido Pedido { get; set; }
    }
}
