//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteNotasDeDescuento
    {
        public int idNotaDeDescuento { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public string fechaTexto { get; set; }
        public int folio { get; set; }
        public decimal monto { get; set; }
        public int idMoneda { get; set; }
        public string descripcionMoneda { get; set; }
        public int idCliente { get; set; }
        public string razonSocial { get; set; }
        public Nullable<int> idFactura { get; set; }
        public string folioFactura { get; set; }
        public Nullable<System.DateTime> fechaFactura { get; set; }
        public int idEstatusDeNotaDeDescuento { get; set; }
    }
}
