//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CambioDivisa
    {
        public int idCambioDivisa { get; set; }
        public int idMonedaDivisa { get; set; }
        public decimal monto { get; set; }
    
        public virtual AbonosDeFactura AbonosDeFactura { get; set; }
        public virtual Moneda Moneda { get; set; }
    }
}
