//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotasDeDescuento
    {
        public int idNotaDeDescuento { get; set; }
        public int folio { get; set; }
        public Nullable<System.DateTime> fechaHora { get; set; }
        public decimal monto { get; set; }
        public string descripcion { get; set; }
        public int idMoneda { get; set; }
        public int idEmpresa { get; set; }
        public int idCliente { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idEstatusDeNotaDeDescuento { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idNotaDeCredito { get; set; }
        public decimal tipoDeCambio { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual EstatusDeNotaDeDescuento EstatusDeNotaDeDescuento { get; set; }
        public virtual Factura Factura { get; set; }
        public virtual Moneda Moneda { get; set; }
        public virtual NotasDeCredito NotasDeCredito { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual CancelacionesDeNotaDeDescuento CancelacionesDeNotaDeDescuento { get; set; }
    }
}
