//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimbresDePago
    {
        public int idTimbreDePago { get; set; }
        public string noCertificado { get; set; }
        public string cadenaOriginal { get; set; }
        public string sello { get; set; }
        public string version { get; set; }
        public string selloSAT { get; set; }
        public string selloCFD { get; set; }
        public string noCertificadoSAT { get; set; }
        public string UUID { get; set; }
        public System.DateTime fechaTimbrado { get; set; }
        public string rfcProvCertif { get; set; }
        public string leyenda { get; set; }
    
        public virtual CancelacionesDeTimbresDePago CancelacionesDeTimbresDePago { get; set; }
        public virtual Pago Pago { get; set; }
    }
}
