//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Series
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Series()
        {
            this.TiposDeComprobantes = new HashSet<TiposDeComprobante>();
        }
    
        public int idSerie { get; set; }
        public string identificador { get; set; }
        public int folioInicial { get; set; }
        public int folioFinal { get; set; }
        public int idConfiguracion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TiposDeComprobante> TiposDeComprobantes { get; set; }
        public virtual Configuracione Configuracione { get; set; }
    }
}
