//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equivalencia
    {
        public int idEquivalencia { get; set; }
        public int idArticulo { get; set; }
        public int idUnidadDeMedida { get; set; }
        public decimal unidades { get; set; }
        public bool activa { get; set; }
    
        public virtual UnidadesDeMedida UnidadesDeMedida { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
