//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteAntiguedadSaldosFactura
    {
        public int idFactura { get; set; }
        public string serie { get; set; }
        public int folio { get; set; }
        public int idCliente { get; set; }
        public Nullable<int> idTipoRelacion { get; set; }
        public Nullable<int> idComprobanteOriginal { get; set; }
        public Nullable<int> FacturaSustituta { get; set; }
        public string codigo { get; set; }
        public string nombreComercial { get; set; }
        public string razonSocial { get; set; }
        public int idMoneda { get; set; }
        public Nullable<int> diasCredito { get; set; }
        public string contacto { get; set; }
        public string telefono { get; set; }
        public int idDomicilio { get; set; }
        public string calle { get; set; }
        public string numeroExterior { get; set; }
        public string numeroInterior { get; set; }
        public string colonia { get; set; }
        public string ciudad { get; set; }
        public string estado { get; set; }
        public int idPais { get; set; }
        public string codigoPostal { get; set; }
        public string nombreDeUsuario { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string moneda { get; set; }
        public System.DateTime fechaHora { get; set; }
        public int idEstatusDeFactura { get; set; }
        public string estatus { get; set; }
        public decimal tipoDeCambio { get; set; }
        public Nullable<decimal> subtotal { get; set; }
        public Nullable<decimal> impuestos { get; set; }
        public Nullable<decimal> abonado { get; set; }
    }
}
