//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Certificado
    {
        public int idCertificado { get; set; }
        public string numero { get; set; }
        public System.DateTime expedicion { get; set; }
        public System.DateTime vencimiento { get; set; }
        public string certificadoBase64 { get; set; }
        public bool activo { get; set; }
        public int idConfiguracion { get; set; }
    
        public virtual Configuracione Configuracione { get; set; }
    }
}
