//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bascula
    {
        public int idBasculaEstacion { get; set; }
        public string puerto { get; set; }
        public int velocidad { get; set; }
        public int tiempoDeLectura { get; set; }
        public int tiempoDeEscritura { get; set; }
        public int bitsDeParada { get; set; }
        public int paridad { get; set; }
        public int bitsDeDatos { get; set; }
        public string finDeLinea { get; set; }
    
        public virtual Estacione Estacione { get; set; }
    }
}
