//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesDeOrdenDeCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallesDeOrdenDeCompra()
        {
            this.Impuestos = new HashSet<Impuesto>();
        }
    
        public int idDetalleDeOrdenDeCompra { get; set; }
        public int idArticulo { get; set; }
        public decimal cantidad { get; set; }
        public decimal costoUnitario { get; set; }
        public int idOrdenDeCompra { get; set; }
        public int idUnidadDeMedida { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        public virtual ComentariosPorDetalleDeOrdenDeCompra ComentariosPorDetalleDeOrdenDeCompra { get; set; }
        public virtual OrdenesDeCompra OrdenesDeCompra { get; set; }
        public virtual UnidadesDeMedida UnidadesDeMedida { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impuesto> Impuestos { get; set; }
    }
}
