//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteImpuestosPorPeriodo
    {
        public string descripcionImpuesto { get; set; }
        public Nullable<int> idImpuesto { get; set; }
        public Nullable<int> idTipoDeImpuesto { get; set; }
        public string descripcionTipoDeImpuesto { get; set; }
        public Nullable<int> idTipoFactor { get; set; }
        public string descripcionTipoDeFactor { get; set; }
        public Nullable<decimal> valorImpuesto { get; set; }
        public Nullable<decimal> baseGravable { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> idFactura { get; set; }
        public Nullable<int> idNotaDeCredito { get; set; }
        public int idMoneda { get; set; }
        public decimal tipoDeCambio { get; set; }
        public System.DateTime fechaHora { get; set; }
    }
}
