//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwSalidasPorArticulo
    {
        public int idArticulo { get; set; }
        public Nullable<decimal> SalidasFacturas { get; set; }
        public Nullable<decimal> EntradasFacturas { get; set; }
        public Nullable<decimal> Facturas { get; set; }
        public Nullable<decimal> SalidasAjustes { get; set; }
        public Nullable<decimal> EntradasAjustes { get; set; }
        public Nullable<decimal> Ajustes { get; set; }
        public Nullable<decimal> SalidasRemisiones { get; set; }
        public Nullable<decimal> EntradasRemisiones { get; set; }
        public Nullable<decimal> Remisiones { get; set; }
        public Nullable<decimal> totalSalidas { get; set; }
        public Nullable<decimal> salidasTraspasos { get; set; }
        public Nullable<decimal> entradasTraspasos { get; set; }
        public Nullable<decimal> Traspasos { get; set; }
    }
}
