//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DatosExtraPorOrdenDeCompra
    {
        public int idOrdenDeCompra { get; set; }
        public string dato { get; set; }
        public string valor { get; set; }
    
        public virtual OrdenesDeCompra OrdenesDeCompra { get; set; }
    }
}
