//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwReporteCostoDeLoVendido
    {
        public Nullable<int> idEstatusDeFactura { get; set; }
        public Nullable<int> idEstatusDeRemision { get; set; }
        public Nullable<decimal> costo { get; set; }
        public int idMonedaArticulo { get; set; }
        public Nullable<decimal> importe { get; set; }
        public string folio { get; set; }
        public System.DateTime fecha { get; set; }
        public string fechaTexto { get; set; }
        public int idCliente { get; set; }
        public string razonSocialCliente { get; set; }
        public string codigoCliente { get; set; }
        public int idMonedaTransaccion { get; set; }
        public string descripcionMoneda { get; set; }
        public int idUsuario { get; set; }
        public string nombreUsuario { get; set; }
        public Nullable<System.DateTime> fechaCancelacion { get; set; }
        public string fechaCancelacionTexto { get; set; }
    }
}
