//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estacione
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estacione()
        {
            this.ImpresorasPorEstacions = new HashSet<ImpresorasPorEstacion>();
        }
    
        public int idEstacion { get; set; }
        public string descripcion { get; set; }
        public string equipo { get; set; }
        public int idEmpresa { get; set; }
    
        public virtual Bascula Bascula { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpresorasPorEstacion> ImpresorasPorEstacions { get; set; }
    }
}
