//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallesDeNotaDeCredito
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetallesDeNotaDeCredito()
        {
            this.PedimentoPorDetalleDeNotaDeCreditoes = new HashSet<PedimentoPorDetalleDeNotaDeCredito>();
            this.Impuestos = new HashSet<Impuesto>();
        }
    
        public int idDetalleDeNotaDeCredito { get; set; }
        public int idNotaDeCredito { get; set; }
        public decimal cantidad { get; set; }
        public int idArticulo { get; set; }
        public decimal precioUnitario { get; set; }
    
        public virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedimentoPorDetalleDeNotaDeCredito> PedimentoPorDetalleDeNotaDeCreditoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Impuesto> Impuestos { get; set; }
        public virtual NotasDeCredito NotasDeCredito { get; set; }
    }
}
