//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudesDeTraspaso
    {
        public int idEmpresaAsociadaOrigen { get; set; }
        public int idTraspaso { get; set; }
        public int folio { get; set; }
        public System.DateTime fechaHora { get; set; }
    
        public virtual EmpresasAsociada EmpresasAsociada { get; set; }
    }
}
