//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VwArticulosVendido
    {
        public System.DateTime FechaHora { get; set; }
        public string Fecha { get; set; }
        public string CodigoArticulo { get; set; }
        public string DescripcionArticulo { get; set; }
        public decimal Cantidad { get; set; }
        public decimal Precio { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public string Moneda { get; set; }
        public string Folio { get; set; }
        public string TipoTransaccion { get; set; }
        public int Cliente { get; set; }
    }
}
