//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aprovi.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdenesDeCompra
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdenesDeCompra()
        {
            this.DatosExtraPorOrdenDeCompras = new HashSet<DatosExtraPorOrdenDeCompra>();
            this.DetallesDeOrdenDeCompras = new HashSet<DetallesDeOrdenDeCompra>();
            this.Compras = new HashSet<Compra>();
        }
    
        public int idOrdenDeCompra { get; set; }
        public int folio { get; set; }
        public System.DateTime fechaHora { get; set; }
        public decimal tipoDeCambio { get; set; }
        public int idMoneda { get; set; }
        public int idProveedor { get; set; }
        public int idUsuarioRegistro { get; set; }
        public int idEmpresa { get; set; }
        public int idEstatusDeOrdenDeCompra { get; set; }
    
        public virtual CancelacionesDeOrdenesDeCompra CancelacionesDeOrdenesDeCompra { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DatosExtraPorOrdenDeCompra> DatosExtraPorOrdenDeCompras { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual Moneda Moneda { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetallesDeOrdenDeCompra> DetallesDeOrdenDeCompras { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual EstatusDeOrdenDeCompra EstatusDeOrdenDeCompra { get; set; }
        public virtual Proveedore Proveedore { get; set; }
    }
}
